# Generated by Django 5.2.7 on 2026-04-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, null=True, unique=True, verbose_name='ID del pago')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del pago')),
                ('tipo_pago', models.CharField(max_length=50, verbose_name='Tipo de pago')),
                ('estado', models.CharField(choices=[('C', 'Completado'), ('P', 'Pendiente'), ('F', 'Fallido')], default='P', max_length=1)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Pagos',
                'db_table': 'pago',
            },
        ),
    ]
