# Generated by Django 5.2.7 on 2026-04-04 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='pedido',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='pedidos.pedido'),
        ),
    ]
