# Generated by Django 5.2.7 on 2026-04-04 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], unique=True, verbose_name='Nombre de la categoría')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(help_text='Ingrese el valor de la talla (L,M,S,XL, etc... )', max_length=10, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tallas',
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del artículo')),
                ('disponible', models.BooleanField(default=True, help_text='Marca si el producto está disponible para compra')),
                ('descripcion', models.TextField(blank=True, max_length=500, verbose_name='Descripción')),
                ('destacado', models.BooleanField(default=False, help_text='Marcar para mostrar en página principal', verbose_name='Producto destacado')),
                ('imagen_articulo', models.ImageField(help_text='Esta será la imagen principal del artículo', null=True, upload_to='articulos/imagenes/', verbose_name='Imagen del artículo')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='tienda.categoriaarticulo', verbose_name='Categoría del artículo')),
            ],
            options={
                'verbose_name_plural': 'Artículos',
                'db_table': 'articulo',
            },
        ),
        migrations.CreateModel(
            name='ImagenArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenes', models.ImageField(help_text='Estas serán las imágenes secundarias del artículo', upload_to='articulos/imagenes/', verbose_name='Imágenes del artículo')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='tienda.articulo', verbose_name='Artículo')),
            ],
            options={
                'verbose_name_plural': 'Imágenes de artículo',
            },
        ),
        migrations.CreateModel(
            name='VarianteArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock disponible')),
                ('precio', models.DecimalField(decimal_places=0, help_text='Sin puntos ni comas', max_digits=12, null=True, verbose_name='Precio base del artículo')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variante_articulo', to='tienda.articulo')),
                ('talla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.talla')),
            ],
            options={
                'unique_together': {('articulo', 'talla')},
            },
        ),
    ]
