# Generated by Django 5.2.7 on 2026-04-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_articulo_imagen_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen_articulo',
            field=models.ImageField(help_text='Esta será la imagen principal del artículo', max_length=255, null=True, upload_to='articulos/imagenes/', verbose_name='Imagen del artículo'),
        ),
    ]
