# Generated by Django 5.2.7 on 2026-04-04 18:44

import pedidos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(default=pedidos.models.numero_pedido, unique=True, verbose_name='Número de pedido')),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('E', 'Enviado'), ('G', 'Entregado'), ('X', 'Cancelado')], default='P', max_length=1)),
                ('nombre_envio', models.CharField(max_length=50, verbose_name='Nombre asociado al envío')),
                ('apellido_envio', models.CharField(max_length=100, verbose_name='Apellido asociado al envío')),
                ('direccion_envio', models.CharField(max_length=50, verbose_name='Dirección asociada al envío')),
                ('datos_adicionales_envio', models.CharField(max_length=50, verbose_name='Datos adicionales del envío')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True, null=True)),
                ('telefono_envio', models.CharField(max_length=50, verbose_name='Teléfono asociado al envío')),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
